name: Sync LeetCode
on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: '0 0 * * *' # Runs daily
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Submissions
        uses: joshcai/leetcode-sync@v1.7 # Check Marketplace for latest version
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
